import "@/styles/globals.scss";
import "@/styles/PageHome.scss";
import "@/styles/search.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ThemeProvider } from "next-theme";
import { RecoilRoot } from "recoil";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <RecoilRoot>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component {...pageProps} />
      </RecoilRoot>
    </>
  );
}
